# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
version: 2

# CodeRabbit Configuration
language: "en-US"

# Review settings
reviews:
  profile: "chill"
  auto_review:
    enabled: true
    base_branches: ["main"]
    ignore_title_keywords:
      - "^docs:"
      - "^chore:"
    labels:
      - "no-review"
      - "dependencies"
  high_level_summary: true
  poem: false
  review_status: true
  collapse_walkthrough: false

  # Path filters for file types to review
  path_filters:
    - "backend-flask/**/*.py"
    - "frontend-react/**/*.{ts,tsx}"

  # Path-specific instructions
  path_instructions:
    - path: "backend-flask/**/*.py"
      instructions: |
        Review Python code for:
        - PEP 8 compliance
        - Type hints usage
        - Proper error handling
        - API consistency
        - Test coverage
    - path: "frontend-react/**/*.{ts,tsx}"
      instructions: |
        Review React/TypeScript code for:
        - TypeScript type safety
        - React best practices
        - Component structure
        - State management
        - Test coverage

# Chat settings
chat:
  auto_reply: true
  language: english
  review_comment_tone: constructive
  integrations:
    github:
      enabled: true

# Knowledge base settings
knowledge_base:
  include_paths:
    - "docs/**"
    - "README.md"
    - "**/README.md"
  exclude_paths:
    - "**/node_modules/**"
    - "**/__pycache__/**"
    - "**/dist/**"
    - "**/build/**"

# Code generation settings
code_generation:
  enabled: true
  docstrings:
    enabled: true
    style: google
  tests:
    enabled: true
    framework: pytest

code_suggestions:
  autofix: false
  validation_level: strict 