#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# Get list of changed files
CHANGED_FILES=$(git diff --cached --name-only)

# Check if backend files changed
if echo "$CHANGED_FILES" | grep -q "^backend-flask/"; then
  cd backend-flask
  poetry run black . && poetry run flake8 && poetry run isort .
  if [ $? -ne 0 ]; then
    echo "Backend checks failed!"
    exit 1
  fi
fi

# Check if frontend files changed
if echo "$CHANGED_FILES" | grep -q "^frontend-react/"; then
  cd frontend-react
  npm run lint && npm run test:staged
  if [ $? -ne 0 ]; then
    echo "Frontend checks failed!"
    exit 1
  fi
fi
